steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - $_FUNC_NAME
  - --gen2
  - --entry-point=$_ENTRY_POINT
  # subscription filterを使用する場合はHTTPエンドポイントになり、インターネット経由のアクセスになるため
  - --ingress-settings=all
  - --max-instances=$_MAX_INSTANCES
  - --memory=$_MEMORY
  - --project=$_PROJECT
  - --region=asia-northeast1
  - --runtime=python311
  - --source=CloudFunctions/PubSubTriggerWithFilterSample/.
  - --timeout=$_TIMEOUT
  - --trigger-http
